# Numpy Indexing and Selection

In [4]:
import numpy as np

In [7]:
#creating simple array
arr=np.arange(0,11)

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
This simplest way to pick one or some elements of array looks very similar to python lists

In [9]:
arr[8]

8

In [10]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

In [12]:
#setting a value with index range(Broadcasting)改变arrary前5个数字
arr[0:5]=100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
# Reset array
arr=np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### slices

In [20]:
slice_of_arr=arr[0:6]

In [21]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [22]:
#change slice 
slice_of_arr[:]=99

In [23]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [24]:
#notice that the change also occur in our original way 
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### The problem is that data is not copied, it's a view of the origianl way, if you want to avoid this, you can use .copy()

In [27]:
arr_copy=arr.copy()

In [28]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices) 
筛选的时候，在内部是遵循左闭又开的。具体的可以见这一张exercise mat那题

In [32]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [33]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr_2d[1]

array([20, 25, 30])

In [35]:
arr_2d[1,1]

25

In [36]:
#上面的表达式也可以用
arr_2d[1][1]

25

In [ ]:
#2d array slicing 
#shape(2,2) from top right corner 

In [51]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [56]:
arr_2d[2]

array([35, 40, 45])

In [59]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

## More Indexing Help
Indexing a 2D matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching *NumPy indexing* to find useful images, like this one:

 Image source: http://www.scipy-lectures.org/intro/numpy/numpy.html

## Conditional Selection 选择性筛选
This is very fundmental concepy that will directly translate to pandas later on,make sure you understand this part! 

In [42]:
arr=np.arange(1,11)

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [46]:
# 这一步好好的理解
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])