In [4]:
import numpy as np

In [2]:
my_list=[1,2,3]

my_array=np.array(my_list)

In [4]:
my_array

array([1, 2, 3])

In [5]:
type(my_array)

numpy.ndarray

In [7]:
type(my_list)

list

# np.arange() 

In [2]:
import numpy as np

In [4]:
np.arange(4)

array([0, 1, 2, 3])

In [5]:
np.arange(4.0)

array([0., 1., 2., 3.])

In [6]:
np.arange(3,7)

array([3, 4, 5, 6])

In [7]:
np.arange(3.0,7.0)

array([3., 4., 5., 6.])

In [9]:
np.arange(3,10,2)

array([3, 5, 7, 9])

array([3, 5, 7, 9])

# np.zeros() & np.ones()

#### np.zeros(shape,dtype=float,ordert='C')
order = 'C', 'F; default is 'C'

In [14]:
np.zeros(5,)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [17]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [22]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

# np.linspace() 

array([3., 6., 9.])

In [12]:
np.arange(3,10,3)

array([3, 6, 9])

In [37]:
np.linspace(3,11,3)

array([ 3.,  7., 11.])

In [38]:
np.linspace(3,12,3)

array([ 3. ,  7.5, 12. ])

In [40]:
np.arange(3,12,3)

array([3, 6, 9])

In [41]:
np.arange(3,12,4)

array([ 3,  7, 11])

### arange()类似于内置函数range()，通过指定开始值、终值和步长创建表示等差数列的一维数组，注意得到的结果数组不包含终值。
### linspace()通过指定开始值、终值和元素个数创建表示等差数列的一维数组，可以通过endpoint参数指定是否包含终值，默认值为True，即包含终值。

## np.eye()  
### Create an identity matrix; Returns a 2D array with ones on the diagonal and zeros elsewhere;

In [ ]:
# 创建一个 以1为对角线的 二维矩阵；其他位置 用0代替；k是缩进值

In [42]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [43]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
# K=1 缩进 1 

In [23]:
np.eye(4,dtype=int,k=1)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [25]:
np.eye(4,k=1,dtype=int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [26]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# Random 
## np.random.rand()

In [ ]:
# 再「0，1」 范围内随机生成值

In [48]:
np.random.rand(3)

array([0.47624443, 0.08556709, 0.43881324])

In [31]:
import numpy as np 
np.random.rand(3,3)

array([[0.69233149, 0.68099709, 0.90508327],
       [0.2121043 , 0.25190171, 0.15435707],
       [0.92340046, 0.09889154, 0.29633807]])

## np.random.randn()

In [ ]:
# 在正态分布 sigma=1 内返回值

In [50]:
np.random.randn(4)

array([-0.21744563, -0.8239816 ,  0.95075563,  0.04066739])

In [52]:
np.random.randn(3,3)

array([[ 0.06064694,  0.48780906,  0.67993263],
       [-0.38389153, -1.91139332, -0.15357503],
       [-0.83259025, -1.95922019, -0.15655846]])

## np.random.randint()

In [53]:
# 左开右闭返回 int 函数, 默认从0开始；

In [54]:
np.random.randint(5)

1

In [55]:
np.random.randint(5)

3

In [56]:
np.random.randint(5,10)

7

In [ ]:
# 加上size 能返回特定数量的值

In [62]:
np.random.randint(5,10,size=(3,2))

array([[6, 7],
       [9, 9],
       [8, 8]])

## np.random.seed()

In [63]:
# can be used to set the random state, so that tne same 'random' 
#results canbe reproduced

In [64]:
np.random.seed(1)
np.random.randint(0,100,size=2)

array([37, 12])

In [65]:
np.random.randint(0,100,size=2)

array([72,  9])

In [ ]:
# 相当于编号一样 很好理解

In [32]:
np.random.seed(1)
np.random.randint(0,100,size=(2,2))

array([[37, 12],
       [72,  9]])

# Array Attributes and Methods

## Reshape

In [69]:
arr=np.arange(25)

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
ranarr=np.random.randint(0,50,10)

In [72]:
ranarr

array([ 8,  9, 11,  5, 15,  0, 16,  1, 12,  7])

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
# reshape

In [75]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [76]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [77]:
# 会报错事因为 reshape 包含20个 但是arr有25个。

In [78]:
ranarr

array([ 8,  9, 11,  5, 15,  0, 16,  1, 12,  7])

In [80]:
ranarr.reshape(2,5)

array([[ 8,  9, 11,  5, 15],
       [ 0, 16,  1, 12,  7]])

In [81]:
ranarr

array([ 8,  9, 11,  5, 15,  0, 16,  1, 12,  7])

## max() min() argmax() argmin()

In [82]:
ranarr.max()

16

In [83]:
ranarr.min()

0

In [85]:
ranarr.argmax()

6

In [86]:
ranarr.argmin()

5

# Shape

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [89]:
arr.shape

(25,)

In [90]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [92]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [93]:
arr.reshape(25,1).shape

(25, 1)

# dtype

In [94]:
arr.dtype

dtype('int64')

In [98]:
arr2=np.array([1.0,2,3,4])

In [99]:
arr2

array([1., 2., 3., 4.])

In [100]:
arr2.dtype

dtype('float64')

## Exercise

In [6]:
myarray=np.linspace(0,10,101)

In [7]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [ ]:
np.arange()